[package]
name = "ctflags"
version = "0.3.6"
edition = "2024"

[dependencies]
dirs = "*"
once_cell = "*"
md5 = "*"
tracing = "*"
pyo3 = { version = "*", features = ["extension-module", "abi3-py37"], optional = true }

[lib]
# "lib" est le type par défaut pour l'écosystème Rust.
# "cdylib" est une librairie dynamique de style C, idéale pour être chargée par d'autres langages.
crate-type = ["lib", "staticlib", "cdylib"]

[features]
default = []
python = ["dep:pyo3"]
