name: Build, test and integrate

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build the library
      run: cargo build --release

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libctflag
        path: target

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Test the library
      run: cargo test

  integrate:
    runs-on: ubuntu-latest
    needs: build
    env:
      CTFLAGS_SEED_FILE_NAME: ctflag.seed
      FLAG_GLOBAL_SALT: "YOURKEY"
    steps:
    - name: Install C++ compiler and dependencies
      run: sudo apt-get update && sudo apt-get install --assume-yes g++

    - name: Download library artifact
      uses: actions/download-artifact@v4
      with:
        name: libctflag
        path: target/

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build the C++ intergration example
      run: g++ -o ./testclient example/testclient.cc -Iinclude -Ltarget/release -lctflags -lpthread -ldl -lm

    - name: Simulate user registration
      run: echo -n segg1545 | tee ${CTFLAGS_SEED_FILE_NAME}

    - name: Run the C++ integration example
      run: ./testclient

