name: Build and test the library

on:
  push:
    branches: [ "*" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Build the library
      run: cargo build --release

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: libctflag
        path: target

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Test the library
      run: cargo test

  build-python:
    runs-on: ubuntu-latest
    needs: build
    env:
      CTFLAGS_SEED_FILE_NAME: ctflag.seed
      FLAG_GLOBAL_SALT: ${{ secrets.FLAG_GLOBAL_SALT }}
    steps:
      - uses: actions/checkout@v4

      #- name: Install Rust
      #  uses: dtolnay/rust-toolchain@stable
      # - uses: actions/setup-python@v5

      - name: Install Maturin
        run: pip install maturin

      - name: Build Wheel
        run: maturin build --release

      - name: Upload Wheel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels
          path: target/wheels/*.whl

      - name: Install Wheel
        # On installe le .whl généré pour vérifier qu'il est valide
        run: pip install target/wheels/*.whl

      - name: Simulate user registration
        run: echo -n segg1545 | tee ${CTFLAGS_SEED_FILE_NAME}

      - name: Test package
        # Petit test inline pour s'assurer que le module se charge et fonctionne
        run: python example/testclient.py

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs:
      - build-python
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          name: python-wheels
          path: target/wheels

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/wheels/*.whl

  integrate:
    runs-on: ubuntu-latest
    needs: build
    env:
      CTFLAGS_SEED_FILE_NAME: ctflag.seed
      FLAG_GLOBAL_SALT: ${{ secrets.FLAG_GLOBAL_SALT }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # - name: Install C++ compiler and dependencies
      #   run: sudo apt-get update && sudo apt-get install --assume-yes g++

      - name: Download library artifact
        uses: actions/download-artifact@v4
        with:
          name: libctflag
          path: target/

      - name: Build the C++ intergration example
        run: g++ -o ./testclient example/testclient.cc target/release/libctflags.a -Iinclude -lpthread -ldl -lm

      - name: Simulate user registration
        run: echo -n segg1545 | tee ${CTFLAGS_SEED_FILE_NAME}

      - name: Run the C++ integration example
        run: ./testclient

